const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const RESET_CART = "RESET_CART";
const UPDATE_QUANTITY = "UPDATE_QUANTITY";

const SORT_BY_PRICE = "SORT_BY_PRICE";
const FILTER_BY_STOCK = "FLITER_BY_STOCK";
const FILTER_BY_DELIVERY = "FILTER_BY_DELIVERY";
const FILTER_BY_RATING = "FILTER_BY_RATING";
const CLEAR_FILTERS = "CLEAR_FILTERS";

const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

export { ADD_TO_CART, REMOVE_FROM_CART, RESET_CART, UPDATE_QUANTITY, SORT_BY_PRICE, FILTER_BY_STOCK, FILTER_BY_DELIVERY, FILTER_BY_RATING, CLEAR_FILTERS, OPEN_MODAL, CLOSE_MODAL };